language: python

sudo: false

cache:
    directories:
      - $HOME/.cache/pip

python:
  - 3.4
  - 3.5
  - 3.6

env:
  - DIST="--installpkg ./dist/pyzac-*.whl"

matrix:
  include:
    - python: 3.5
      env:
        - TOXENV=regression
        - TIMEOUT=travis_wait 45
        - WITH_COVERAGE=1

install:
  - pip install -r requirements.txt
  - pip list
  - python setup.py bdist_wheel

script:
  - $TIMEOUT tox -v $DIST