language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.6
env:
- DIST="--installpkg ./dist/pyzac-*.whl"
install:
- pip install -r requirements.txt
- pip list
- python setup.py bdist_wheel
script:
- "$TIMEOUT tox -v $DIST"
- cd docs; make html linkcheck

deploy:
  provider: pypi
  user: DarkLight
  password:  
    secure: C5FyR9xUcX1HCaj0KkJxjZSfr/dwkTKTngMgHzBqvaBETGFKEYVXbnohprgSr4VmI0GOubuF+SxjfrMXhQ7cblSdB7lg8qpZ9rhNKs0xrxhmnVAdCmVv+pYM8U+KALn9VoKW+/K6mkCJ4fBeuK7cs74w+VoT7KQxm0ijp82SzP+yZ/GJ2qK9KtsyMbvswdk80LQ1fmpqRp68vF0PkTakYx0/aOHU3SSSFlzffbaEx/1ej3zH681Dx8n7upLMB5x6yd77WaFZSmdOYTcKyPb7A9EwayNUWDJIqc1HnoBoTsyKDdy5rdcXhh+hswtqQFDp0c1dOXDFIekc9eeO8gBvPXiGsPIyXgmjrgJW7+dFWvYGQiMAkHyRGpA0ers6qKJNvKr7m734AMls/NeQjUq7Yy+JtDcmSsDtqiX+MXkx6rkdLDaaS0BNzWVWBFFx6b68jprnHkj5FzmngELk0Ewv37peVEqyf7R9V8FtmggW+1vlKGliatNMm/05t0aJ1fDbBDk/58eAtNKAdhBh8vqQwNILcSfXUQ1W7wim/tAw31ocSTAe7vzEfPOpIE3qWFEXoP2omTAEEs6FBvhtnMKJ06cy9f2d8xCRfprPLfKFsPFjChbDPpJjD+/r2dxW9OxRRZms6NjIeytPpVVLl3sFTKBnZCk2ED84U3TnkZM7M0w=
