language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.6
env:
- DIST="--installpkg ./dist/pyzac-*.whl"
install:
- pip install -r requirements.txt
- pip list
- python setup.py bdist_wheel
script:
- "$TIMEOUT tox -v $DIST"
deploy:
  provider: pypi
  user: DarkLight
  password:
    secure: V11Uq8HONMLIwsdIA20cPsTiVz0iewosZHhl8leO+iRuKihWFuqoby3+gPdENGEd4rc//jeL5MVbsfOB9PB2of54pomgcu1lC5sOQEEL3f35gm/1hN2fDxx/E7tp3a+UIxFrjc50dfVwAgb9/NvaW49beZazumtsvkGUUsEwWjdR8OImlGdi7a3HsNtMLd/k8nFgE7r3T6vv1w8yESJm2sR3fm05i4m1We5fpkY7sKlqWU/F7nT77erAK5cti/LdsS4nJAEPSLfsfQH7qXwHHX2Q1QmD0PlobMP+ml0mon9qv2e1EwHuDHtVug5EKwxq8HU3lARCWvs3/IbEO/Mymau1n/EEfbb4sB2OQtJ7xRDQtvSRtCPAJOtIPvjTOxXpOuhdAaB9Z/ifqYa9P21WhfUKUMOYGA7/di6nuGRpo1cg5ecPl2FN/GRRgGHeuAXBjmx5q0nwa+XGX1ClQqSNnwWKUJQ3L7vnr/fBqKRm7ZcIiEwDs4+BBbT0oOZfQ3D/xsi57GrQu11SEy4rVPa4duwMs9uJzKtnfQh/WrvkxpB0AnB0iwrkaPL+fHXLzjncpLUgvqhktA+0YipfRR7Z6HPAmEwQNnnzCHlpqM3UnPW75V5KdKGmQnCew6l6GXOItQ9sJJX+xZH+RDQCZFtxt4HihgmcL6/VCqDHMapCPf8=
