language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.6
env:
- DIST="--installpkg ./dist/pyzac-*.whl"
install:
- pip install -r requirements.txt
- pip list
- python setup.py bdist_wheel
script:
- "$TIMEOUT tox -v $DIST"
deploy:
  provider: pypi
  user: DarkLight
  password:
    secure: BAhD7YI1m2f59E1D1jEst4rbW9AeEJ6Q90h+HzWPYGEx1YYHgy9rsL3g5NPxYlMWizwZ+FAmOU8uyjI/PDelj8zCWUyHJDe9dLzWknQf4otJDzd24Ps7LhxXenD2J0MK1Oxw5fKnjhfGwoEYRFcR/DwsiXq07otPu9JLIH+ITLuSPKYYRnJJx8OwIPsXGYPyygUuTpA0AgFgnlQ9lkHlRq1Q3me1S/fFXSTrp1hhEe6atDDCo/nfeWwrwnnewL1xV2OBuoFmt0T/hBLdDzaDoEbxp5754gCIaYFvjZXDNJxtQ3wmrG1zV7FYTQKbKh0cIWVcjWQ9eekJBGG0yFfDoXY81gXq3taKiit6fy8ol59LdvlpnS2Qi7rfLwaUttSErbc2rcuX0ME+iIisTWDSOagOrcMNkACLd4uA9Oxal4NFr3we6sdUtxWw2CKj/HNS/6zf4qdKhcLkW3p3r7qbQ2nzk5+wqsfWOwz9FI7OEWtl9/pXb3X6FbGKvfQY3503Bl5SeuUUnGJHAejFDk1Qwxw7/BN1MMYnvJ3xlQq/L1ZWKYHzokjg4p1rgm8RZh09KETGVy6nBbie10N8uybRxfHrIKkpo7HDxkLODztQqe9TTRTqUpXKC46NfVS+eJ3FOZUIQJjAzzShSTTWyUi97+idvt0dxptnTk1mk/fYstQ=
