language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.6
env:
- DIST="--installpkg ./dist/pyzac-*.whl"
install:
- pip install -r requirements.txt
- pip list
- python setup.py bdist_wheel
script:
- "$TIMEOUT tox -v $DIST"
deploy:
  provider: pypi
  user: DarkLight
  password:
    secure: QNabXymsgkC7YNVV74Hbhx6uFQMWLduxUuLvlPeX3Hs8+Wv8AANGDTAOmpuA37oY3w1qmEk1KqtP25b0wWPMYjTwgaLIsNU2FHQ9EdHxYYLXBVivN4/vu5Drp1Miui9b0BuXblwXKC9t1nV7lzBdkMPRmt0kt3G1eZaclIef/wkYG9OILbl2+efd41Kh/9AZD4sUmfMJ0JCpnr8QGwoLqUZ+LIYPbjGvNN04NP9XnOaO0039/xY0ZBvihCdeOPk73qUS4l1SHxK32v53g3jQ0ne/g1NsZYCjuQzcP4YC5eQ3AJqKrBtnYFOfWD+xRFIrGKaIYLpDAmg9f4gPgVBygkJpnF3vY9p6m6N7iP9Omty4UI6XRP8SLht5QKwH2YAkzjC/Mac35NxlMBImxZCtFrENLPpY2se2oYQDpG5ferr1UQWDhgpL8PYrgExE3smbgJZHfrnRgq1Oz5N8cl/MdhQ3I+PB7CxXeT0w7JWnn+x7HJhZ1+mJEi1c0tHs93vS8tqS/vvjp2utocAG0hea45gyd/InutUEuxbKoTQt8L7l9qZwB7y+4dOXCS/wHVbGa+C6uQX17GJoOgQSw+UBc3/zmi3GHxZoaUFyjecR4DZ89w5uTkYe16shpSBThhGMtISf1rL77UVlxUnKdLu2wDUbwoOg/5/QXAIvD2jgz08=
